### ISSUE TITLE
There was an error when the code page could not be obtained

### ISSUE THREAD

**Issue by wll8** [coderaiser/win32#1]
![image](https://user-images.githubusercontent.com/28223260/174237825-e9cfc980-046e-4732-8313-aeae2a3c59bb.png)

![image](https://user-images.githubusercontent.com/28223260/174236286-f0495560-92d5-4736-aa79-8a337d4b4a34.png)

**Comment by coderaiser** [comment]
Is it works for you now?

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝
